openapi: 3.0.0
info:
  title: Mejai API
  description: >
    환영합니다! [Mejai.gg](https://example.com)는 League of Legends의 게임 데이터를 분석하여 사용자에게 통계를 제공하는 서비스입니다. 이 API 문서는 Mejai.gg의 API를 사용하는 방법을 설명합니다.
    
    #### 지원 및 문의
    - API 사용 중에 문제가 발생하거나 추가적인 지원이 필요한 경우, 지원 페이지에서 도움을 받을 수 있습니다.
    - 새로운 기능 제안이나 버그 리포트는 리포지토리를 통해 제출해 주세요.
    
    #### API 작성에 참고한 문서:
    - [Google API design guide](https://cloud.google.com/apis/design)

  contact:
    email: wnddms12345@gmail.com
  version: 0.0.1

externalDocs:
  description: Find out more about Mejai GG
  url: http://example.com

servers:
  - url: http://127.0.0.1:8080

paths:
  /users/profile:
    get:
      tags:
        - Users
      summary: 소환사 정보 조회
      description: >
        이 API는 주어진 소환사 ID를 사용하여 소환사의 프로필 정보를 조회합니다. 반환된 정보에는 소환사의 ID, 프로필 아이콘 URL, 티어, 티어 이미지 URL, 랭크, 리그 포인트, 승리 및 패배 횟수가 포함됩니다.
      operationId: getUsersProfile
      parameters:
        - name: id
          in: query
          required: true
          description: 소환사 아이디
          schema:
            type: string
            example: 'Hide on bush'
        - name: tag
          in: query
          required: false
          description: 소환사 태그
          schema:
            type: string
            example: 'KR'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: 기타 오류
        '404':
          description: 해당 소환사 정보 찾을 수 없음
        '405':
          description: 잘못된 메소드로 요청

  /users/streak:
    get:
      tags:
        - Users
      summary: 소환사 게임 횟수 조회
      description: >
        소환사가 특정 기간 동안 진행한 게임의 총 횟수를 조회합니다. 사용자는 소환사 ID, 조회 시작 날짜, 조회 종료 날짜를 제공하여 해당 기간 동안 소환사가 진행한 게임의 수를 날짜별로 확인할 수 있습니다.
      operationId: getUserGameCounts
      parameters:
        - name: id
          in: query
          required: true
          description: 소환사 아이디
          schema:
            type: string
            example: 'Faker'
        - name: startDate
          in: query
          required: true
          description: 조회 시작 날짜
          schema:
            type: string
            format: date
            example: '2021-10-01'
        - name: endDate
          in: query
          required: true
          description: 조회 종료 날짜
          schema:
            type: string
            format: date
            example: '2021-10-31'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGameCount'
        '400':
          description: 기타 오류
        '404':
          description: 해당 소환사 정보 찾을 수 없음
        '405':
          description: 잘못된 메소드로 요청

components:
  schemas:
    UserProfile:
      type: object
      properties:
        userId:
          type: string
          description: 소환사 아이디
          example: 'Hide on bush'
        profileIcon:
          type: string
          format: uri
          description: 소환사 프로필 이미지 URL
          example: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/profileicon/588.png'
        tier:
          type: string
          description: 소환사 티어
          example: 'CHALLENGER'
        tierImage:
          type: string
          format: uri
          description: 소환사 티어 이미지 URL
          example: 'https://opgg-static.akamaized.net/images/medals/challenger_1.png'
        rank:
          type: string
          description: 소환사 티어 랭크
          example: 'I'
        leaguePoint:
          type: number
          description: 소환사 리그 포인트
          example: 864
        wins:
          type: number
          description: 소환사 랭크 승리 횟수
          example: 131
        losses:
          type: number
          description: 소환사 랭크 패배 횟수
          example: 100
    UserGameCount:
      type: object
      properties:
        date:
          type: string
          format: date
          description: 게임한 날짜
          example: '2021-10-10'
        gameCount:
          type: number
          description: 해당 날짜에 진행된 게임 횟수
        examples:
          example1:
            value: 3
            summary: 낮은 게임 횟수
          example2:
            value: 7
            summary: 높은 게임 횟수
          example3:
            value: 5
            summary: 중간 게임 횟수
