spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mejai
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate.SQL: debug
