spring:
  datasource:
    # you must change url to docker database container name
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
variables:
  resourceURL: "d1lgkfcquwlbly.cloudfront.net"
